### ISSUE TITLE
TODO: After release

### ISSUE THREAD

**Issue by GeTtOo** [GeTtOo/SCP-Breach-CSGO#1]
This section presents a list of features that we will try to add after the release.

- [x] ?World Text ent
- [x] Multiple Model Values ​​for Player Classes
- [ ] Possibility of choosing the method of searching for players when the reactor explodes (By height or in a certain zone)
- [ ] More dimensions for SCP-106 
- [ ] Custom weapon
- [ ] Editing the list of items that spawn on the map through the admin menu
- [ ] ?An array of doors id that will be closed after the explosion
- [ ] Rework SCP-106 collide (based on SDKHook_ShouldCollide).
